name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.0', '8.1', '8.2' ]
    steps:
    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php-versions }}"
        coverage: xdebug

    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install merge clover
      run: |
        cd clover
        composer install --prefer-dist --no-progress

    - name: Create folder
      run: mkdir -p build/logs && mkdir -p spec/public

    - name: Run test suite
      run: |
        ./vendor/bin/kahlan --reporter=verbose --coverage=4 --clover=clover-kahlan.xml
        ./vendor/phpunit/phpunit/phpunit --configuration phpunit.xml --teamcity

    - name: Merge clover
      run: |
            cd clover
            ./vendor/bin/clover-merge merge -o ../build/logs/clover.xml ../clover.xml ../clover-kahlan.xml

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: 2c8e02c733427a8a315db588b680f39011c144fffaaa6bea88695113e798222b

    - name: Create Badge Version
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 44652f42dbbd9f45f3f640a9197baeec/raw/e74d5c0bddce135d91031ff3cb3b7c7fc0cdff47/version.json
        filename: version.json
        label: Version Php
        message: ${{ matrix.php-versions }}
        color: orange